default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.9

ci:
    skip: [pytest-check, shelf-commit-msg]
    autofix_commit_msg: |
        🚧 [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_schedule: weekly
    autoupdate_commit_msg: |
        🚧 [pre-commit.ci] pre-commit autoupdate

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev:  v3.17.0
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus", "--keep-runtime-typing"]
        stages: [ Nonepre-commitNone ]

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        stages: [ Nonepre-commitNone ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev:  v0.6.9
    hooks:
    -   id: ruff
        args:
        - --fix
        stages: [ Nonepre-commitNone ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v5.0.0
    hooks:
    -   id: fix-byte-order-marker
        stages: [ Nonepre-commitNone ]
    -   id: trailing-whitespace
        stages: [ Nonepre-commitNone ]
    -   id: end-of-file-fixer
        stages: [ Nonepre-commitNone ]
    -   id: check-yaml
        stages: [ Nonepre-commitNone ]
        args: ["--unsafe"]
    -   id: check-toml
        stages: [ Nonepre-commitNone ]

-   repo: https://github.com/korawica/clishelf
    rev: v0.2.8
    hooks:
    -   id: shelf-commit-msg

-   repo: local
    hooks:
    -   id: pytest-check
        name: PyTest Runner
        stages: [ Nonepre-pushNone ]
        types: [ python ]
        entry: venv/Scripts/pytest.exe -v
        language: system
        pass_filenames: false
        always_run: true
