# docs: https://github.com/marketplace/actions/python-coverage-comment
name: ci

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          #  - "3.9"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements-tests.txt') }}-test-v03

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -e .[dev,test]

      - run: mkdir coverage

      - name: Run coverage and produce a .coverage file
        run: |
          coverage run -m pytest --disable-pytest-warnings
        env:
          COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
#          CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}

      - run: ls -al

      - name: Store coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  coverage:
    # This make sure the workflow is skipped without any alert.
    # if: ${{ false }}
    name: coverage
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write

      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Get coverage files
        uses: actions/download-artifact@v3
        id: download
        with:
          name: coverage
          path: coverage

      - run: |
          pip install "coverage[toml]"
          pip install "pytest>=7.1.3,<8.0.0"

      - run: ls -al coverage
      - run: |
          coverage combine coverage
          coverage report --show-missing
          coverage html --show-contexts --title "Coverage for ${{ github.sha }}"

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: warning
          COMMENT_ARTIFACT_NAME: coverage-comment-action
          COMMENT_FILENAME: coverage-comment-action.txt
          COVERAGE_DATA_BRANCH: coverage

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: coverage-comment-action
          path: coverage-comment-action.txt

      - name: Store coverage HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: htmlcov

      - run: coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # This job does nothing and is only used for the branch protection
  # docs: https://github.com/marketplace/actions/alls-green
  check:
    if: always()
    needs:
      - build
      - coverage
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
