name: test

on:
  push:
    branches: [
      "main",
      "*.*.*",
      "migration",
    ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest  # `windows-latest`
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache your dependencies (i.e. all the stuff in your `pyproject.toml`).
      - uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key:  ${{ runner.os }}-python-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-v04

      # The `if` statement ensures this only runs on a cache miss.
      - name: Install Python Dependencies
        if:  steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install --upgrade pip
          uv pip install -e .
          uv pip install "pytest>=7.4.3,<8.0.0"

      - name: Use Python virtual environment
        run: |
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV

      - name: Check git is working
        run: |
          git config --global user.email "korawica@github.actions"
          git config --global user.name "Testing Git on Travis CI"
          git --version
          git config --list

      - name: Test with Pytest
        run: |
          pytest -v
